version: 2
name: custom
displayName: Custom MCP Servers
registry:
  xian:
    description: "Interface with XIAN blockchain for wallet management and transactions"
    title: "XIAN Network"
    type: server
    dateAdded: "2025-01-29T00:00:00Z"
    image: xian-mcp-server:latest
    ref: ""
    readme: ""
    toolsUrl: ""
    source: ""
    upstream: ""
    icon: ""
    tools:
      - name: create_wallet
      - name: create_wallet_from_private_key
      - name: create_hd_wallet
      - name: get_balance
      - name: send_transaction
      - name: send_tokens
      - name: submit_contract
      - name: get_state
      - name: get_contract
      - name: simulate_transaction
      - name: sign_message
      - name: encrypt_message
      - name: decrypt_message
    secrets:
      - name: XIAN_NODE_URL
        env: XIAN_NODE_URL
        example: "https://node.xian.org"
      - name: XIAN_CHAIN_ID
        env: XIAN_CHAIN_ID
        example: "xian-1"
    metadata:
      category: integration
      tags:
        - blockchain
        - cryptocurrency
        - xian
        - wallet
        - smart-contracts
      license: MIT
      owner: local